### ISSUE TITLE
Formless conditionals issue

### ISSUE THREAD

**Issue by Lyzon** [space10-community/conversational-form#310]
Hi, team! this is a wonderful project, thank you for the hard work!
I got a issue when I use Formless & conditional questions.

- I have provided a code example.
https://stackblitz.com/edit/vue-conversational-form-q6dxcf?file=myForm.js

- If I encountered an issue I have provided:
  - a description of the actual and expected behavior
The gif how the error shows: https://i.bmp.ovh/imgs/2019/07/dfbd8f12a7533f4e.gif (can you see it?)
After the condition question displayed. I click the previous question and change the answer. then we will got the error:
Error in /turbo_modules/conversational-form@0.9.90/dist/conversational-form.js (4867:32)
Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

  - what version of Conversational Forms I am using
0.9.90
  - what browser and version I am using
Chrome 75.0.3770.100
  - the output of the browser console

conversational-form.js?3aed:4867 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.

```at ChatResponse.addSelf (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:4867:32)
    at ChatResponse.processResponseAndSetText (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:4819:18)
    at ChatResponse.setValue (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:4679:22)
    at ChatList.setCurrentUserResponse (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:5142:38)
    at ChatList.onUserInputUpdate (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:4989:22)
    at EventDispatcher.dispatchEvent (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:394:32)
    at onValidationCallback (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:5289:39)
    at FlowManager.userInputSubmit (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:5304:13)
    at EventDispatcher.dispatchEvent (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:394:32)
    at UserTextInput.doSubmit (webpack-internal:///./node_modules/conversational-form/dist/conversational-form.js:4546:30)```

**Comment by jenssogaard** [comment]
@Lyzon thank you for the kind words. I am sorry that you ran into this bug. It will be fixed in the upcoming v1.0.0 which will hopefully be released within a couple of weeks.

**Comment by Lyzon** [comment]
@jenssogaard Thank you so much!

**Comment by jenssogaard** [comment]
@Lyzon you reopened this issue. Do you have anything to add?

**Comment by Lyzon** [comment]
Hi,  @jenssogaard I need your help again.
After upgrade conversational-form v1.0.1, I got a different issue when I do the same opration. The gif(https://i.bmp.ovh/imgs/2019/07/dfbd8f12a7533f4e.gif) shows my opration and I got this error:

`conversational-form.js?3aed:5024 Uncaught TypeError: Cannot read property 'robot' of null
    at ChatResponse.processResponseAndSetText (conversational-form.js?3aed:5024)
    at ChatResponse.setValue (conversational-form.js?3aed:4858)
    at ChatList.setCurrentUserResponse (conversational-form.js?3aed:5362)
    at ChatList.onUserInputUpdate (conversational-form.js?3aed:5209)
    at EventDispatcher.dispatchEvent (conversational-form.js?3aed:394)
    at onValidationCallback (conversational-form.js?3aed:5510)
    at eval (conversational-form.js?3aed:5493)
    at eval (ConversationForm.vue?9127:177)
    at complete (index.js?8f07:89)`

The codepen link: https://stackblitz.com/edit/vue-conversational-form-q6dxcf?file=package.json

Hope you can fix this!

Thank you so much!!!

**Comment by Lyzon** [comment]
And also, I notice that I add event listener `UserInputEvents.FOCUS`, but it didn't work. I check  `FlowEvents.USER_INPUT_UPDATE` event works fine.
see it on the codepen:
https://stackblitz.com/edit/vue-conversational-form-q6dxcf?file=myForm.js
